### ISSUE TITLE
What is remapped exactly?

### ISSUE THREAD

**Issue by sohnemann** [simonescanzani/universal_mx_keys_remap#1]
Hello,

I've stumbled upon your script today and I was hoping it would fix my issue with the 'option' key being too far to the right, because of the new 'fn' key in-between. Unfortunately nothing has changed really, so I was wondering, what you are exactly mapping.

Cheers,
sohnemann

**Comment by silverback97** [comment]
Hi,
First of all, have you set the mapping on windows? If not this script won't work. 
The guide is quite old and I forgot to specify that you have to install another mouse driver first, you won't use the mouse but you'll need it to generate a dummy device.

https://support.logi.com/hc/it/articles/360024847553--Download-Mouse-M705-Marathon

If you use the script for the Unifying device the left "option" and left "command" switch themselves. In case you have set the fixed keyboard mapping on windows the right "command" is already "option/altGr" while the right "option" becomes your right "command".

If you need further help don't hesitate to write me or send me the screens of the steps you've made or the configuration in the Logi options app.

Everything I've written is based on the documentation Apple has written for the keyboard mappings. By following the codes that I have used I will surely understand what I have changed in the normal configuration of the MX Keys:

https://developer.apple.com/library/archive/technotes/tn2450/_index.html

Remember that these scripts are written for Italian keyboards. 

Cheers,
Simone.

**Comment by sohnemann** [comment]
Hi Simone,

thank you for your reply. I was unaware that this was for an italian keyboard in Windows mode.  😅
I have since found a solution utilizing Karabiner Elements. I remapped the right Command key to be an Option key,
thus not using the FN key or Option key at all.

Cheers,
sohnemann

**Comment by ideadapt** [comment]
I have just figured out that I had to change the productId in the script. You can find your keyboards product id in the system report (https://stackoverflow.com/questions/54392510/how-to-assign-a-key-remapping-to-specific-device-using-hidutil).
