### ISSUE TITLE
Mapping key combinations

### ISSUE THREAD

**Issue by AjianNie** [simonescanzani/universal_mx_keys_remap#5]
Is it applicable to the latest MX Keys S keyboard and mapping key combinations? 

Also, is there a simple way to obtain the "Source Key on mac" like "0x7000000e2"?

**Comment by silverback97** [comment]
This method I use is actually applicable to any keyboard, as long as it is identified with a specific ID by the system.

Look at the remapkeys.sh file, you will see that there is the field '{"ProductID":0x408a}'.
You need to change that ID to the target keyboard ID.
With Logitech with Unifying technology that is the ProductID.

To answer your question: you just need to find the ProductID associated with Logitech's BOLT module.
Once this is done, you can edit the script yourself.


Also, if you want to map the key with another, still in the same remapkeys.sh script, you will find an array of json objects.
Create another json type object
_{"HIDKeyboardModifierMappingSrc":0x7000000e3, "HIDKeyboardModifierMappingDst":0x7000000e2}_
by modifying HIDKeyboardModifierMappingSrc with the HEX value of the key you need, and insert in HIDKeyboardModifierMappingDst which one you need to map.
